import jsPDF from 'jspdf';
import 'jspdf-autotable';

export const generateExpensePDF = (expenses, categories = []) => {
  const doc = new jsPDF();

  // Add title
  doc.setFontSize(20);
  doc.setTextColor(40, 40, 40);
  doc.text('Smart Expense Tracker', 105, 20, { align: 'center' });

  // Add subtitle
  doc.setFontSize(14);
  doc.setTextColor(100, 100, 100);
  doc.text('Expense Report', 105, 30, { align: 'center' });

  // Add date
  doc.setFontSize(10);
  doc.setTextColor(150, 150, 150);
  const currentDate = new Date().toLocaleDateString();
  doc.text(`Generated on: ${currentDate}`, 105, 40, { align: 'center' });

  // Calculate summary statistics
  const totalExpenses = expenses.length;
  const totalAmount = expenses.reduce((sum, expense) => sum + parseFloat(expense.amount), 0);
  const averageAmount = totalExpenses > 0 ? totalAmount / totalExpenses : 0;

  // Category breakdown
  const categoryBreakdown = {};
  expenses.forEach(expense => {
    const categoryName = getCategoryName(expense.category_id, categories);
    if (!categoryBreakdown[categoryName]) {
      categoryBreakdown[categoryName] = { count: 0, total: 0 };
    }
    categoryBreakdown[categoryName].count++;
    categoryBreakdown[categoryName].total += parseFloat(expense.amount);
  });

  // Add summary section
  doc.setFontSize(12);
  doc.setTextColor(40, 40, 40);
  doc.text('Summary', 20, 60);

  doc.setFontSize(10);
  doc.setTextColor(80, 80, 80);
  doc.text(`Total Expenses: ${totalExpenses}`, 20, 70);
  doc.text(`Total Amount: $${totalAmount.toFixed(2)}`, 20, 80);
  doc.text(`Average Amount: $${averageAmount.toFixed(2)}`, 20, 90);

  // Category breakdown table
  let yPosition = 110;
  if (Object.keys(categoryBreakdown).length > 0) {
    doc.setFontSize(12);
    doc.setTextColor(40, 40, 40);
    doc.text('Category Breakdown', 20, yPosition);

    const categoryData = Object.entries(categoryBreakdown).map(([category, data]) => [
      category,
      data.count,
      `$${data.total.toFixed(2)}`,
      `$${(data.total / data.count).toFixed(2)}`
    ]);

    doc.autoTable({
      startY: yPosition + 10,
      head: [['Category', 'Count', 'Total Amount', 'Average']],
      body: categoryData,
      theme: 'grid',
      styles: {
        fontSize: 9,
        cellPadding: 3,
      },
      headStyles: {
        fillColor: [59, 130, 246], // Blue color
        textColor: 255,
        fontStyle: 'bold',
      },
      alternateRowStyles: {
        fillColor: [248, 250, 252], // Light gray
      },
    });

    yPosition = doc.lastAutoTable.finalY + 20;
  }

  // Expenses table
  doc.setFontSize(12);
  doc.setTextColor(40, 40, 40);
  doc.text('Expense Details', 20, yPosition);

  const tableData = expenses.map(expense => [
    new Date(expense.date).toLocaleDateString(),
    expense.title || 'N/A',
    getCategoryName(expense.category_id, categories),
    `$${parseFloat(expense.amount).toFixed(2)}`,
    expense.notes || ''
  ]);

  doc.autoTable({
    startY: yPosition + 10,
    head: [['Date', 'Title', 'Category', 'Amount', 'Notes']],
    body: tableData,
    theme: 'striped',
    styles: {
      fontSize: 8,
      cellPadding: 2,
    },
    headStyles: {
      fillColor: [59, 130, 246], // Blue color
      textColor: 255,
      fontStyle: 'bold',
    },
    columnStyles: {
      0: { cellWidth: 25 }, // Date
      1: { cellWidth: 35 }, // Title
      2: { cellWidth: 30 }, // Category
      3: { cellWidth: 25 }, // Amount
      4: { cellWidth: 'auto' }, // Notes
    },
    alternateRowStyles: {
      fillColor: [248, 250, 252], // Light gray
    },
  });

  // Add footer
  const pageCount = doc.internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text(`Page ${i} of ${pageCount}`, 105, 285, { align: 'center' });
    doc.text('Generated by Smart Expense Tracker', 105, 290, { align: 'center' });
  }

  // Save the PDF
  const filename = `expenses_${new Date().toISOString().split('T')[0]}.pdf`;
  doc.save(filename);
};

const getCategoryName = (categoryId, categories) => {
  if (!categoryId) return 'Uncategorized';
  const category = categories.find(cat => cat.id === categoryId);
  return category ? category.name : 'Unknown Category';
};
